name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-pc-windows-gnu
        profile: minimal
        override: true

    - name: Build binary
      run: cargo build --release

    - name: Prepare artifact
      run: |
        mkdir artifact
        copy target\release\rod_calc.exe artifact\

    - name: Upload to Release
      if: github.event_name == 'release'
      uses: ncipollo/release-action@v1
      with:
        artifacts: artifact/rod_calc.exe
        tag: ${{ github.event.release.tag_name }}
