name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Publish binaries
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      id: build
      run: |
        cargo build --release
        $file_version = (Get-Item ./target/release/rot_calc.exe).VersionInfo.FileVersion
        "VERSION=$file_version" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/rot_calc.exe
        asset_name: rot_calc.exe
        tag: ${{ steps.build.outputs.VERSION }}
        overwrite: true
        body: "release"
